create table QUIZ1(id bigint auto_increment, name varchar(255));

select ID, NAME from QUIZ


insert into QUIZ (name) values ('Test Quiz')

UPDATE QUIZ SET NAME='Quiz Test 2' WHERE ID = 1;
DELETE QUIZ  WHERE ID = 1;

CREATE TABLE QUESTIONS (QUIZ_ID INT, QUESTION_ID bigint auto_increment,  QUESTION_TEXT VARCHAR(255), TOPIC VARCHAR(255), DIFFICULTY INT, QUESTION_TYPE VARCHAR(1), HINT VARCHAR(50), PRIMARY KEY(QUIZ_ID,QUESTION_ID));

CREATE TABLE MCQChoice(QUESTION_ID INT, ANSWER_ID INT , ANSWER_TEXT VARCHAR(255), VALID BOOLEAN, PRIMARY KEY (QUESTION_ID , ANSWER_ID));