CREATE TABLE USERS ( USER_ID VARCHAR(255) PRIMARY KEY, PASSWORD VARCHAR(255), STUD_FLAG VARCHAR(255));
insert into USERS values ('stud','stud','S');
insert into USERS values ('admin','admin','A');

CREATE TABLE QUIZ (ID bigint auto_increment PRIMARY KEY, NAME VARCHAR(255));

CREATE TABLE QUESTIONS (QUIZ_ID INT, QUESTION_ID bigint auto_increment,  QUESTION_TEXT VARCHAR(255), TOPIC VARCHAR(255), DIFFICULTY INT, QUESTION_TYPE VARCHAR(1), HINT VARCHAR(50), PRIMARY KEY(QUIZ_ID,QUESTION_ID));

CREATE TABLE MCQChoice(QUESTION_ID INT, ANSWER_ID INT , ANSWER_TEXT VARCHAR(255), VALID BOOLEAN, PRIMARY KEY (QUESTION_ID , ANSWER_ID));