CREATE TABLE USERS ( USER_ID  PRIMARY KEY, PASSWORD VARCHAR(255), STUD_FLAG VARCHAR(255));

CREATE TABLE QUIZ (ID INT, NAME VARCHAR(255));

CREATE TABLE QUESTIONS (QUIZ_ID INT, QUESTION_ID bigint auto_increment,  QUESTION_TEXT VARCHAR(255), TOPIC VARCHAR(255), DIFFICULTY INT, QUESTION_TYPE VARCHAR(1), HINT VARCHAR(50), PRIMARY KEY(QUIZ_ID,QUESTION_ID));

CREATE TABLE MCQChoice(QUESTION_ID INT, ANSWER_ID INT , ANSWER_TEXT VARCHAR(255), VALID BOOLEAN, PRIMARY KEY (QUESTION_ID , ANSWER_ID));